# Refer https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis
sudo: false
language: ruby

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
 - bundle exec jekyll build
 - bundle exec rake test
